on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch origin master
      - uses: longfangsong/another-criterion-compare-action@v0.1-beta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
