on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jasonwilliams/criterion-compare-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
